## Template script for creating new UIFlow pages via right-click menu.
## This is a placeholder — the actual content is generated by the plugin.
extends UIFlowPage

func _on_created(_data: Variant = null) -> void:
	super._on_created(_data)

func _on_opened(_data: Variant = null) -> void:
	super._on_opened(_data)

func _on_hidden() -> void:
	super._on_hidden()

func _on_shown() -> void:
	super._on_shown()

func _on_closed() -> void:
	super._on_closed()

func _on_destroyed() -> void:
	super._on_destroyed()
